// Code generated by hertz generator.

package demo

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"hz/demo/biz/model/hz/demo"
)

// QueryMsg .
// @router msg/query [GET]
func QueryMsg(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.QueryRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo.QueryResponse)

	c.JSON(consts.StatusOK, resp)
}
