// Code generated by hertz generator.

package demo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _msgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querymsgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _deletemsgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _insertmsgMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _updatemsgMw() []app.HandlerFunc {
	// your code...
	return nil
}
